### ISSUE TITLE
Auto-delete temp files or download them to directory specified in config

### ISSUE THREAD

**Issue by MrVideo** [metafates/mangal#10]
When I press `r` on a manga to read the single chapter, Mangal downloads it to a temporary directory on my Mac.

I think it would be better for the manga downloaded with this option to be saved in the directory specified in the config file. 

Another plausible solution would be to auto-delete the temporary file when quitting Mangal.

**Comment by metafates** [comment]
Thanks for feedback!

Okay, so you mean downloading readable chapter to the path specified by `download_path` option in config? If that's the case then I think it's not very convenient, since if you're trying to read chapter instead of downloading it, you don't want to produce any additional files.

Or maybe you're saying that there should be an additional option that specifies where to store readable chapters?

About auto-deleting, yes, I will add this, thanks. You can also use `mangal cleanup` to remove all cached and temp files

**Comment by MrVideo** [comment]
Honestly, it could be both! I think being able to specify the `temp` folder could be a good addition, but I see your point.

I also did not notice the `mangal cleanup` command, my bad there, that kind of solves everything on its own.

Thank you!
