### ISSUE TITLE
Volume Mode

### ISSUE THREAD

**Issue by matthewsimo** [metafates/mangal#12]
**Is your feature request related to a problem? Please describe.**
It would be cool to be able to grab entire volumes instead of by chapter.

**Describe the solution you'd like**
A flag or something to add a step to roll up chapters into a single pdf for each volume.

**Describe alternatives you've considered**
n/a

**Additional context**
Obviously pretty dependent on structure of the manga since some don't use volumes but just an idea..

**Comment by metafates** [comment]
Thanks for suggesting!

That's a cool idea but... 

...unfortunately I don't think I'll be able to implement it since manga sites rarely provide such information and adapting scrapers to it will make overall logic of app way more complex than it needs to be (and than I'm capable of maintaining)

However, I will consider this feature when I'll be making a more advanced scraper system in the future

**Comment by metafates** [comment]
It's now possible with the new inline mode

```
mangal inline --source Manganelo --query "death note" --manga first --chapters "@Vol.1 @"  -d
```

Notice the `--chapters "@Vol.1 @"` - it will select all chapters with the "Vol.1 " substring in their names
