### ISSUE TITLE
Error exit status 3

### ISSUE THREAD

**Issue by laluxx** [metafates/mangal#138]
### Describe the bug

everytime i try to read a manga it trows the following error:
could not open /tmp/mangal/[0001]_Chapter_1_Uzumaki_Naruto.pdf with : exit status 3

### Reproduction steps

1 installed using yay [aur/mangal-bin 4.0.4-1]]
2 open the tui app whit the command "mangal"
3 any source leads to the same error
4 search for any anime 
5 select any chapter

### Expected behavior

open the manga chapter

### Additional context

OS  :  Arch Linux
Package : aur/mangal-bin 4.0.4-1

### Operating System

Linux

**Comment by metafates** [comment]
Hi!

I guess the problem is that you don't have [xdg-open](https://linux.die.net/man/1/xdg-open) command installed (used to open files with default app).

You can check if it's installed or not with this command

```shell
command -v xdg-open
```

If it's installed, then, according to the [manpage](https://linux.die.net/man/1/xdg-open) exit status 3 means

> A required tool could not be found.

Do you have any pdf reader installed? Such as zathura, or any other. If you do, then try to specify it explicitly

```shell
# example if you use zathura
mangal config set -k reader.pdf -v  zathura
```

Hope that helps
