### ISSUE TITLE
Where are logs located?

### ISSUE THREAD

**Issue by Buronn** [metafates/mangal#60]
I need to know where logs (example: search or find selector) are located
thanks :)

**Comment by OmiChrome** [comment]
bro first my grammer is waek explain me this 

why not equal  ?
Where logs are located?= Where are logs located?

**Comment by Buronn** [comment]
> 
English is not my native language and I almost always get confused in the order of some things ngl, even more when I write fast

**Comment by OmiChrome** [comment]
dang boi 
but still u din't answer that 
coz my english more bad T_T


why not equal ?
Where logs are located?= Where are logs located?

**Comment by metafates** [comment]
@Buronn Hello! Unfortunately, there aren't any logging mechanism implemented yet. I'll add it in the next version (I hope)

**Comment by OmiChrome** [comment]
btw , im lookign for more update ASAP :)

**Comment by Buronn** [comment]
> @Buronn Hello! Unfortunately, there aren't any logging mechanism implemented yet. I'll add it in the next version (I hope)

@metafates Thanks for the quick response, I was thinking that an option to detect if the page is cascading or not, and set the selector to click on that button would also be nice (because if it isn't, it doesn't work properly)

**Comment by metafates** [comment]
@Buronn I have to admit that the way mangal scrapes pages is very plain, there aren't much sites that fit the requirements, so adding custom scrapers is almost impossible to be honest. I'm working on adding embedded scripting language to define scrapers with options like using headless chrome, complex css selectors and JS execution. I have huge progress with it in my another project [vivi](https://github.com/metafates/vivi) (there aren't any docs or readme yet). So now I know how to do it and I'll try to add it to mangal but not sure when because right now I'm kinda tired

**Comment by OmiChrome** [comment]
🙏 
 pray for your work now  🙏
