### ISSUE TITLE
Image: Unknown format

### ISSUE THREAD

**Issue by peerobo** [metafates/mangal#77]
### Describe the bug

Download chapter get "Image: Unknown format" error

### Reproduction steps

1. Use mangal TUI
2. Choose first source
3. Input "Nozo"
4. Choose "Nozo x Kimi"
5. Select chapter 39
6. Get the error: "Unknown format"

### Expected behavior

Download complete

### Operating System

Linux

**Comment by metafates** [comment]
Hello! Thank you for opening an issue. The problem is that PDF converter (default) is unable to transform some images to pdf format. There isn't much I can do about it since mangal uses [this pdf processor](https://github.com/pdfcpu/pdfcpu). But I'll look into it, maybe that's my fault

## Solution

Try other formats such as
 - `mangal -F plain` - just downloads images
 - `mangal -F cbz` - Comic Book Zip format. [learn more](https://fileinfo.com/extension/cbz)
 - `mangal -F zip` - Packs images to zip archive

**Comment by metafates** [comment]
I see, the problem is that this chapter has a gif as the last image. That's why it can't be converted to PDF. I'll try to make an option to exclude such images to avoid errors

**Comment by peerobo** [comment]
> I see, the problem is that this chapter has a gif as the last image. That's why it can't be converted to PDF. I'll try to make an option to exclude such images to avoid errors

Thanks 👍 This tool is wonderful and you are awesome 👌
