### ISSUE TITLE
Volume Packer

### ISSUE THREAD

**Issue by edgehub-cloud** [metafates/mangal#92]
### Feature Description

Having All chapters inside a single volume

### Solution you would like

pack all chapter inside a single volume cbz {with option if possibel to add a ongoing volume {because if user adds a volume that is ongoing, adds again , the client would have to unzip , check existing , and add new images of the latest chapter , further complicating the process, unless dev can possibly give a try}

### Alternatives you have considered

extracting images out of the cbz in the volume folder and repacking furhter outsourcing a internal feature.

**Comment by metafates** [comment]
I think cbz should contain only a single chapter and link it to the volume with [ComicInfo.xml metadata](https://anansi-project.github.io/docs/category/comicinfo) (mangal generates it). So it's up to a manga reader you're using to handle this rather than downloading a whole volume into a single file. What do you think?

**Comment by edgehub-cloud** [comment]
@metafates the issue comes because comictagger doesn't supports chapters nor comicvine has chapter issues meta data.

**Comment by metafates** [comment]
I see. Well, I can make it an option, sure

**Comment by edgehub-cloud** [comment]
Thanks

**Comment by edgehub-cloud** [comment]
Much awaiting for update/volume packing feature , any progress so far? Thanks again for considering

**Comment by metafates** [comment]
Hi, I remember about it, but I'm very busy at the university right now. You can monitor progress [here](https://github.com/metafates/mangal/blob/dev/CHANGELOG.md). This is a development branch.

Also, there are some problems appeared which I didn't think of, such as tracking pages count, writing valid metadata, and overall complexity of implementing this due to the project design. As an alternative, mangal would fetch manga metadata (genres, tags, summary and so on) from [Anilist](https://anilist.co)

**Comment by edgehub-cloud** [comment]
Good luck mate, thanks again

**Comment by metafates** [comment]
Closing this for now, since new version fetches metadata itself, but I may return to this later
